### ISSUE TITLE
Drag a TaskListDock window from the TaskListCollection to QMainWindow

### ISSUE THREAD

**Issue by jay2044** [jay2044/ADM-2#2]
### Subtasks:
- [x] Make the new dock window appear at the location it was dropped.
- [x] upadte the TaskListDockStacked when changes are made in the TaskListDock.
- [x] check if task_list_updated is working for delete add edit and the sorts.

**Comment by jay2044** [comment]
- [ ] also save and load the settings of all the docks when they are closed and reopened.
