### ISSUE TITLE
Init Advanced Task List.

### ISSUE THREAD

**Issue by jay2044** [jay2044/ADM-2#6]
- [x] determine its variables and functions
- [x] implement the class in task_manager.py
- [x] create schema
- [x] implement a custom widget in gui.py
- [x] create custom control functions to add and interact/edit
